const menu = [
    {
      id: 1,
      title: 'KLUB SENDVIČ',
      category: 'dorucak',
      price: 649,
      img: './images/item-1.jpg',
      desc: `piletina, jaje, pržena slanina, paradajz, pomfrit `,
    },
    {
      id: 2,
      title: 'NJOKE SA ČETIRI VRSTE SIRA POSUTE HRSKAVIM PARMEZANOM',
      category: 'rucak',
      price: 899,
      img: './images/item-2.jpg',
      desc: `gorgonzola, ementaler, gauda, parmezan `,
    },
    {
      id: 3,
      title: 'WHITE LADY',
      category: 'dezerti',
      price: 499,
      img: './images/item-3.jpg',
      desc: 'mus od bele čokolade punjen malinama, pistaći, sorbe od maline',
    },
    {
      id: 4,
      title: 'ENGLESKI DORUČAK',
      category: 'dorucak',
      price: 495,
      img: './images/item-4.jpg',
      desc: `jaja po želji, kobasice, slanina, paradajz, pečurke, pasulj `,
    },
    {
      id: 5,
      title: 'LJUTKASTE PENE SA BIFTEKOM I MOCARELOM',
      category: 'rucak',
      price: 1130,
      img: './images/item-5.jpg',
      desc: 'paradajz sos, čili pasta, rukola, masline',
    },
    {
      id: 6,
      title: 'PALAČINKE',
      category: 'dezerti',
      price: 395,
      img: './images/item-6.jpg',
      desc: 'nutela, eurokrem, plazma, med, orasi, džem, višnje, bela linolada',
    },
    {
      id: 7,
      title: 'CHORIZO & EGGS',
      category: 'dorucak',
      price: 495,
      img: './images/item-7.jpg',
      desc: `jaja na oko, mladi krompir, sitno seckana kobasica, sušeni paradajz, spanać, feta sir `,
    },
    {
      id: 8,
      title: 'VELTOLINA',
      category: 'rucak',
      price: 1140,
      img: './images/item-8.jpg',
      desc: 'goveđa pršuta, pelat, pizza sir, rukola, čeri paradajz, parmezan',
    },
    {
      id: 9,
      title: 'TRADICIONALNI BEOGRADSKI DORUCAK',
      category: 'dorucak',
      price: 249,
      img: './images/item-9.jpg',
      desc: 'kafa sikteruša, dve Lucky Strike cigarete',
    },
  ];
  export default menu;